### PR TITLE
RHMAP-7026 moved to NPM dependency for fh-js-sdk

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
Waiting for RHMAP-9099 to be ready for review to review both at the same time

**Comment by jcesarmobile** [comment]
Deployed on http://testing.juliolarge.skunkhenry.com/#projects

@danielpassos @secondsun 👀?

**Comment by jcesarmobile** [comment]
ah, to download the .apk / .ipa you have to remove the s from https on the download url

**Comment by secondsun** [comment]
When I try to add android to the project locally I get the error "Error: Error validating package name. Package name must look like: com.company.Name"

**Comment by secondsun** [comment]
Works in Android.  

When I view the project in Studio I get a popup with "test" as a message.  Is that related to these changes?

**Comment by jcesarmobile** [comment]
No, I just replaced the whole main.js code with an alert('test'); in my sample app, just to make sure that when the apk/ipa is built the main.js is regenerated on npm install instead of having the data it had on studio. 
If you create your own fh-advanced-hybrid-blank-app app on studio it should have the same main.js that is on this PR.

**Comment by secondsun** [comment]
@jcesarmobile Ok, then I am +1

**Comment by jcesarmobile** [comment]
The only thing is, this PR is not compatible with the preview yet. Not sure if we should merge it now and worry about the preview later or don't merge until it's compatible.

To make it compatible we should do something like what @edewit did on this PR https://github.com/feedhenry-templates/quickstart-backbone-app/pull/6/files (the most important part is the init.js)

And last mail from John said that we should only add fh-js-sdk as npm dependency for now. My PR add jquery as npm dependency too, Erik's PR add Backbone and underscore. So maybe we should remove them and keep the old script tags and files.

**Comment by edewit** [comment]
@jcesarmobile merging now, I'll create a separate PR for the preview update.

**Pull request merged**
